server {
    listen       80;
    server_name  localhost;

    root   /usr/share/nginx/html;

    location ~* /assets/config/init\.js$ {
        expires -1;
        add_header Cache-Control "no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0" always;
    }

    location = /{{MODULE_NAME}}/index.html {
        expires -1;
    }

    location / {
        try_files $uri $uri/ @index;
    }

    location @index {
        expires -1;
        try_files /{{MODULE_NAME}}/index.html =404;
    }

    error_page   500 502 503 504  /50x.html;
}
