export enum Unidade {
  UNIDADE = 'UNIDADE',
  PECA = 'PECA',
  PACOTE = 'PACOTE',
  CAIXA = 'CAIXA',
  FARDO = 'FARDO',
  DUZIA = 'DUZIA',
  PAR = 'PAR',
  KIT = 'KIT',
  CONJUNTO = 'CONJUNTO',
  JOGO = 'JOGO',
  ROLO = 'ROLO',
  SACO = 'SACO',
  LATA = 'LATA',
  GALAO = 'GALAO',
  FRASCO = 'FRASCO',
  TUBO = 'TUBO',
  BARRA = 'BARRA',
  CHAPA = 'CHAPA',
  METRO = 'METRO',
  METRO_QUADRADO = 'METRO_QUADRADO',
  METRO_CUBICO = 'METRO_CUBICO',
  CENTIMETRO = 'CENTIMETRO',
  MILIMETRO = 'MILIMETRO',
  QUILOGRAMA = 'QUILOGRAMA',
  GRAMA = 'GRAMA',
  TONELADA = 'TONELADA',
  LITRO = 'LITRO',
  MILILITRO = 'MILILITRO'
}

export const UnidadeLabels: Record<Unidade, string> = {
  [Unidade.UNIDADE]: 'Unidade',
  [Unidade.PECA]: 'Peça',
  [Unidade.PACOTE]: 'Pacote',
  [Unidade.CAIXA]: 'Caixa',
  [Unidade.FARDO]: 'Fardo',
  [Unidade.DUZIA]: 'Dúzia',
  [Unidade.PAR]: 'Par',
  [Unidade.KIT]: 'Kit',
  [Unidade.CONJUNTO]: 'Conjunto',
  [Unidade.JOGO]: 'Jogo',
  [Unidade.ROLO]: 'Rolo',
  [Unidade.SACO]: 'Saco',
  [Unidade.LATA]: 'Lata',
  [Unidade.GALAO]: 'Galão',
  [Unidade.FRASCO]: 'Frasco',
  [Unidade.TUBO]: 'Tubo',
  [Unidade.BARRA]: 'Barra',
  [Unidade.CHAPA]: 'Chapa',
  [Unidade.METRO]: 'Metro',
  [Unidade.METRO_QUADRADO]: 'Metro quadrado',
  [Unidade.METRO_CUBICO]: 'Metro cúbico',
  [Unidade.CENTIMETRO]: 'Centímetro',
  [Unidade.MILIMETRO]: 'Milímetro',
  [Unidade.QUILOGRAMA]: 'Quilograma',
  [Unidade.GRAMA]: 'Grama',
  [Unidade.TONELADA]: 'Tonelada',
  [Unidade.LITRO]: 'Litro',
  [Unidade.MILILITRO]: 'Mililitro'
};
