spring:
  application:
    name: venda

  datasource:
    url: jdbc:postgresql://db.apcode.com.br/apvenda-dbname
    username: apvenda-dbuser
    password: apvenda-dbpasswd
    driver-class-name: org.postgresql.Driver
    hikari:
      pool-name: apvenda-pool
      initializationFailTimeout: 0
      connectionTimeout: 30000

  jpa:
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        enable_lazy_load_no_trans: true

  security:
    oauth2:
      client:
        registration:
          "[com.github.andrepenteado.venda]":
            provider: com.github.andrepenteado.sso.portal
            client-name: APvenda
            client-id: PRODUCAO-venda
            client-secret: 5f78b637-c57b-416d-9900-b5c83e3cf925
            authorization-grant-type: authorization_code
            scope: openid
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            client-authentication-method: client_secret_basic
        provider:
          "[com.github.andrepenteado.sso.portal]":
            issuer-uri: https://login.apcode.com.br
  web:
    error:
      include-message: always

server:
  forward-headers-strategy: framework
  port: 8080
  servlet:
    context-path: /venda-backend
    session:
      cookie:
        same-site: lax
        http-only: true
        secure: true
        name: venda-backend-session
      timeout: 30m

management:
  endpoints:
    web:
      exposure:
        include:
          - prometheus
          - health
  health:
    livenessState:
      enabled: true
    readinessState:
      enabled: true
  tracing:
    sampling:
      probability: 1.0
    export:
      zipkin:
        endpoint: http://sistemas.apcode.com.br:9411

frontend:
  base-url: https://sistemas.apcode.com.br # CORS
  base-path: /venda